### ISSUE TITLE
Alterar dados próprios

### ISSUE THREAD

**Issue by fcoelho** [semcomp/semcomp-beta#10]
Pessoas podem querer alterar dados próprios delas, sejam os dados quais forem.

Pergunta: isso vai ser necessário? Tá ligado como #3 de novo, e que dados que alguém pode querer alterar?

**Comment by bruno-azenha** [comment]
As pessoas não vão ter a capacidade de alterar seus próprios dados. Uma vez que elas nem tem um login propriamente dito.
