### ISSUE TITLE
As imagens upadas para o site não são recuperáveis pelo front-end

### ISSUE THREAD

**Issue by bruno-azenha** [semcomp/semcomp-beta#15]
Provavelmente algum problema no path no qual as imagens são salvas e a forma como elas são buscadas depois.

**Comment by fcoelho** [comment]
"upadas" quer dizer imagens de que fez upload mesmo? se for isso, ver 1fdd3a699a3bc13ecb8e14cad2ddbbe73c0413ae

**Comment by bruno-azenha** [comment]
Pois é... A gente não está entendendo tão bem onde que as imagens são salvas e como recuperá-las.

**Comment by fcoelho** [comment]
https://docs.djangoproject.com/en/1.7/topics/files/

[MEDIA_URL](https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-MEDIA_URL)
[MEDIA_ROOT](https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-MEDIA_ROOT)

**Comment by leosampaio** [comment]
Fixed by pull request #20 :smile_cat:
