### ISSUE TITLE
Fazer reestruturação do front visando o Single Page Design

### ISSUE THREAD

**Issue by bruno-azenha** [semcomp/semcomp-beta#16]
A página da beta vai ser muito curta para ter uma nav bar no formato atual.

**Comment by carlosasj** [comment]
Você acha que seria suficiente apenas comentar/apagar o código da barra, ou você tem a intenção que cada seção do site seja exibida na tela inteira, uma por vez? (por exemplo: http://designmodo.com/qards/ onde cada scroll é uma nova "tela")

**Comment by bruno-azenha** [comment]
Ficou lindo como está agora!
